### ISSUE TITLE
Handlers "config" attribute is replaced by an empty object

### ISSUE THREAD

**Issue by christian-roggia** [ory/oathkeeper-maester#49]
Assume the following configuration:
```yaml
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: hub-animeshon
  namespace: oathkeeper
spec:
  authenticators:
    - handler: anonymous
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: id_token
      config:
        ttl: 3600s
        claims: |
          {
            "aud": [ "hub.animeapis.dev" ],
            "session": {{ .Extra | toJson }}
          }
  match:
    url: <{https,http}>://hub.animeshon.dev/<**>
    methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS", "HEAD"]
```

The translated `Rule` is missing the `mutators[0].config` attribute:
```json
[
  {
    "upstream": {
      "url": "",
      "preserve_host": false
    },
    "id": "hub-animeshon.oathkeeper",
    "match": {
      "url": "<{https,http}>://hub.animeshon.dev/<**>",
      "methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE",
        "OPTIONS",
        "HEAD"
      ]
    },
    "authenticators": [
      {
        "handler": "anonymous"
      },
      {
        "handler": "cookie_session"
      }
    ],
    "authorizer": {
      "handler": "allow"
    },
    "mutators": [
      {
        "handler": "id_token",
        "config": {}
      }
    ]
  }
]
```

---

Notice that the following block is not as expected:
```json
{
  "mutators": [
    {
      "handler": "id_token",
      "config": {}
    }
  ]
}
```

This is how a correctly applied rule should look like:
```json
{
  "mutators": [
    {
      "handler": "id_token",
      "config": {
        "ttl": "3600s",
        "claims": " {\n \"aud\": [ \"hub.animeapis.dev\" ],\n \"session\": {{ .Extra | toJson }}\n }"
      }
    }
  ]
}
```

**Comment by dennislemonmarkets** [comment]
I get the same error with the JWT authenticator config. It also gets replaced with a empty object. I am using version v.0.1.2

**Comment by christian-roggia** [comment]
It doesn't work with 0.1.3 either.

**Comment by janiskemper** [comment]
It's not only the mutators, but also authenticators and authorizers!

**Comment by Demonsthere** [comment]
Hi there, I will try to take a look into it, as this is something that should be covered by tests. Moreover, a quick check from my end:

```yaml
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-handlers
  namespace: default
spec:
  configMapName: some-cm
  description: Sample rule
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    methods: ["GET"]
    url: <http|https>://foo.bar
  authenticators:
    - handler: anonymous
      config:
        foo: bar
        long: |
            {
              "bar": "foo"
            }
  authorizer:
    handler: allow
    config:
      lorem: ipsum
      answer: 42
  mutators:
    - handler: noop
      config: {}
```

Produced:

```json
{
        "upstream": {
          "url": "http://abc.ef",
          "preserve_host": false
        },
        "id": "sample-rule-handlers.default",
        "match": {
          "url": "<http|https>://foo.bar",
          "methods": [
            "GET"
          ]
        },
        "authenticators": [
          {
            "handler": "anonymous",
            "config": {
              "foo": "bar",
              "long": "{\n  \"bar\": \"foo\"\n}\n"
            }
          }
        ],
        "authorizer": {
          "handler": "allow",
          "config": {
            "answer": 42,
            "lorem": "ipsum"
          }
        },
        "mutators": [
          {
            "handler": "noop",
            "config": {}
          }
        ],
        "configMapName": "some-cm"
      }
```
