### ISSUE TITLE
bearer_token authenticator is not available

### ISSUE THREAD

**Issue by raman-nbg** [ory/oathkeeper-maester#57]
**Describe the bug**

It is not possible to configure a rule of handler type `bearer_token`. Applying the rule gets rejected with `validation error in Rule iam/sample-rule-1: "invalid handlers: [authenticator/bearer_token], please check the configuration"`

I think this happens because the handler is not listed as a default authenticator in https://github.com/ory/oathkeeper-maester/blob/master/main.go#L41

**To Reproduce**

Create any rule with handler `bearer_token`

```yaml
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: sample-rule-1
spec:
  upstream:
    url: "http://abc.ef"
    preserveHost: false
  match:
    methods: ["GET"]
    url: <http|https>://localhost:8080
  authenticators:
    - handler: bearer_token
  authorizer:
    handler: allow
  mutators:
    - handler: noop
      config: {}
```

**Expected behavior**

It should be possible to configure a rule with bearer_token authenticator out of the box.

**Environment**

- Version: `oathkeeper-0.23.2` (which installs the oathkeeper-maester)
- Environment: Kubernetes

**Additional context**

-
